In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['thesisda', 'thesisdata']


In [2]:
data = pd.read_csv("../input/thesisda/final.csv")
print(data)

      id  'age'   'bp'   'sg'  'al'   ...    'cad' 'appet' 'pe' 'ane' 'class'
0      1   48.0   80.0  1.020   1.0   ...       no    good   no    no     ckd
1      2    7.0   50.0  1.020   4.0   ...       no    good   no    no     ckd
2      3   62.0   80.0  1.010   2.0   ...       no    poor   no   yes     ckd
3      4   48.0   70.0  1.005   4.0   ...       no    poor  yes   yes     ckd
4      5   51.0   80.0  1.010   2.0   ...       no    good   no    no     ckd
5      6   60.0   90.0  1.015   3.0   ...       no    good  yes    no     ckd
6      7   68.0   70.0  1.010   0.0   ...       no    good   no    no     ckd
7      8   24.0    NaN  1.015   2.0   ...       no    good  yes    no     ckd
8      9   52.0  100.0  1.015   3.0   ...       no    good   no   yes     ckd
9     10   53.0   90.0  1.020   2.0   ...       no    poor   no   yes     ckd
10    11   50.0   60.0  1.010   2.0   ...       no    good   no   yes     ckd
11    12   63.0   70.0  1.010   3.0   ...       no    poor  yes 

In [3]:
X= np.array(data.iloc[:,1:25].values)
Y=np.array(data.iloc[:,25].values)
print(Y)

['ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd'
 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'ckd' 'c

In [4]:
val = [5,6,7,8,18,19,20,21,22,23]
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
for v in val :
    X[:, v] = labelencoder_X.fit_transform(X[:, v])

labelencoder_y = LabelEncoder()
Y = labelencoder_y.fit_transform( Y)

print(X)
print(Y)


[[48.0 80.0 1.02 ... 1 1 1]
 [7.0 50.0 1.02 ... 1 1 1]
 [62.0 80.0 1.01 ... 2 1 2]
 ...
 [12.0 80.0 1.02 ... 1 1 1]
 [17.0 60.0 1.025 ... 1 1 1]
 [58.0 80.0 1.025 ... 1 1 1]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [5]:
from sklearn.preprocessing import Imputer

miss= [1,2,3,4,9,10,11,12,13,14,15,16,17]
print(X[:2])
calcul=X[:,v ].reshape(-1,1)

imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:5])
z=np.array(X[:, 1:3])
X[:, 1:5] = imputer.transform(X[:, 1:5])
z1=np.array(X[:, 1:5])

imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 9:18])
z=np.array(X[:, 9:18])
X[:, 9:18] = imputer.transform(X[:, 9:18])
z1=np.array(X[:, 9:18])
print(X[:2])

[[48.0 80.0 1.02 1.0 0.0 0 2 1 1 121.0 36.0 1.2 nan nan 15.4 44.0 7800.0
  5.2 2 2 1 1 1 1]
 [7.0 50.0 1.02 4.0 0.0 0 2 1 1 nan 18.0 0.8 nan nan 11.3 38.0 6000.0 nan
  1 1 1 1 1 1]]
[[48.0 80.0 1.02 1.0 0.0 0 2 1 1 121.0 36.0 1.2 137.5176282051282
  4.62724358974359 15.4 44.0 7800.0 5.2 2 2 1 1 1 1]
 [7.0 50.0 1.02 4.0 0.0 0 2 1 1 148.0365168539326 18.0 0.8
  137.5176282051282 4.62724358974359 11.3 38.0 6000.0 4.707434944237917 1
  1 1 1 1 1]]


/opt/conda/lib/python3.6/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
