In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/digit-recog/train.csv
/kaggle/input/digit-recog/sample_submission.csv
/kaggle/input/digit-recog/test.csv


In [2]:
from PIL import Image, ImageDraw
from sklearn import datasets

In [3]:
test = pd.read_csv('/kaggle/input/digit-recog/test.csv')

In [4]:
train= pd.read_csv('/kaggle/input/digit-recog/train.csv')

In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [6]:
print("Loading dataset...")
clf = KNeighborsClassifier(n_neighbors=5)


Loading dataset...


In [7]:
train_x = test[:10000]
train_y = train[:10000]


In [8]:
print("Train model")
clf.fit(train_x, train_y)


Train model


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [9]:
test_x = test[10000:10100]
expected = train[10000:10100].values.tolist()


In [10]:
print("Compute predictions")
predicted = clf.predict(test_x)
print(predicted)


Compute predictions
[[6 0 0 ... 0 0 0]
 [7 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]
 ...
 [3 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
from sklearn.metrics import mean_squared_error

In [12]:
print(mean_squared_error(expected,predicted)/100)

73.16458


In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [14]:
clfs = RandomForestClassifier(n_estimators=5)

In [15]:
train_x = test[:10000]
train_y = train[:10000]

In [16]:
print("Train model")
clfs.fit(train_x, train_y)

Train model


MemoryError: could not allocate 26340229120 bytes

In [17]:
test_x = test[10000:11000]
expected = train[10000:11000].values.tolist()

In [18]:
print("Compute predictions")
predicted = clf.predict(test_x)

Compute predictions


In [19]:
print(mean_squared_error(expected,predicted)/100)

73.58765913375797
