In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris-dataset/iris.data.csv
/kaggle/input/daily-sun-spot-data-1818-to-2019/sunspot_data.csv


In [2]:
#1 Write a python program using Scikit_learn to print the keys, number of rows-columns , feature names and the description of the iris data.
import pandas as pd
iris_data = pd.read_csv("../input/iris-dataset/iris.data.csv")
print("\nKeys of Iris dataset:")
print(iris_data.keys())
print("\nNumber of rows and columns of Iris dataset:")
print(iris_data.shape)


Keys of Iris dataset:
Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

Number of rows and columns of Iris dataset:
(149, 5)


In [3]:
#2 Write a python program to get the number of observations,missing values and nan values.
import pandas as pd
iris = pd.read_csv("../input/daily-sun-spot-data-1818-to-2019/sunspot_data.csv")
print(iris.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73718 entries, 0 to 73717
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                73718 non-null  int64  
 1   Year                      73718 non-null  int64  
 2   Month                     73718 non-null  int64  
 3   Day                       73718 non-null  int64  
 4   Date In Fraction Of Year  73718 non-null  float64
 5   Number of Sunspots        73718 non-null  int64  
 6   Standard Deviation        73718 non-null  float64
 7   Observations              73718 non-null  int64  
 8   Indicator                 73718 non-null  int64  
dtypes: float64(2), int64(7)
memory usage: 5.1 MB
None


In [4]:
#3 Write a python program to create a 2-D array with ones on the diagonal and zeroes elsewhere.
import numpy as np
from scipy import sparse
eye = np.eye(6)
print("NumPy array:\n", eye)
sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n", sparse_matrix)

NumPy array:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

SciPy sparse CSR matrix:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0


In [5]:
#4 Write a python program to load the iris data framefrom a given csv file into a dataframe and print the shape of the data, type of the data and first 3 rows.
import pandas as pd
data = pd.read_csv("../input/iris-dataset/iris.data.csv")
print("Shape of the data:")
print(data.shape)
print("\nData Type:")
print(type(data))
print("\nFirst 3 rows:")
print(data.head(3))

Shape of the data:
(149, 5)

Data Type:
<class 'pandas.core.frame.DataFrame'>

First 3 rows:
   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
