In [1]:
#Q1.printing the keys, number of rows-columns, feature names 
#and the description of the Iris data.
import pandas as pd
iris_data = pd.read_csv("../input/iris-dataset/iris.data.csv")
print("\nKeys of Iris dataset:")
print(iris_data.keys())
print("\nNumber of rows and columns of Iris dataset:")
print(iris_data.shape)
print("Data type:")
print(type(iris_data))


Keys of Iris dataset:
Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

Number of rows and columns of Iris dataset:
(149, 5)
Data type:
<class 'pandas.core.frame.DataFrame'>


In [2]:
#Q2.get the number of observations, missing values and nan values.
print("No.of Observations are:")
print(iris_data.count().sum())
print("No. of Nan is:")
print(iris_data.isnull().sum())

No.of Observations are:
745
No. of Nan is:
5.1            0
3.5            0
1.4            0
0.2            0
Iris-setosa    0
dtype: int64


In [3]:
#Q3.create a 2-D array with ones on the diagonal and zeros elsewhere.
import numpy as np
from scipy import sparse
eye = np.eye(5)
print("NumPy array:\n", eye)
sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n", sparse_matrix)

NumPy array:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

SciPy sparse CSR matrix:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0


In [4]:
#Q4.load the iris data from a given csv file into a dataframe and 
#print the shape of the data, type of the data and first 3 rows.
print("Shape of the data:")
print(iris_data.shape)
print("\nData Type:")
print(type(iris_data))
print("\nFirst 3 rows:")
print(iris_data.head(3))

Shape of the data:
(149, 5)

Data Type:
<class 'pandas.core.frame.DataFrame'>

First 3 rows:
   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
