In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['mnist_train.csv', 'mnist_test.csv']


In [2]:
#import dataset.....
dataset_train = pd.read_csv("../input/mnist_train.csv")
print(dataset_train)
dataset_test = pd.read_csv("../input/mnist_test.csv")
print(dataset_test)

       label  1x1  1x2  1x3  1x4  ...    28x24  28x25  28x26  28x27  28x28
0          5    0    0    0    0  ...        0      0      0      0      0
1          0    0    0    0    0  ...        0      0      0      0      0
2          4    0    0    0    0  ...        0      0      0      0      0
3          1    0    0    0    0  ...        0      0      0      0      0
4          9    0    0    0    0  ...        0      0      0      0      0
5          2    0    0    0    0  ...        0      0      0      0      0
6          1    0    0    0    0  ...        0      0      0      0      0
7          3    0    0    0    0  ...        0      0      0      0      0
8          1    0    0    0    0  ...        0      0      0      0      0
9          4    0    0    0    0  ...        0      0      0      0      0
10         3    0    0    0    0  ...        0      0      0      0      0
11         5    0    0    0    0  ...        0      0      0      0      0
12         3    0    0   

In [3]:
#feature initializing...
y_train = np.array(dataset_train.iloc[:,0])
X_train = np.array(dataset_train.iloc[:,1:])
X_test = np.array(dataset_test.iloc[:,1:]) 
y_test = np.array(dataset_test.iloc[:,0])
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
print(X_train , y_train)
print(X_train.shape)
print(y_test.shape)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [5 0 4 ... 5 6 8]
(60000, 784)
(10000,)


In [4]:
#onehot encoding.....
from keras.utils import np_utils
y_train = np_utils.to_categorical(y_train, 10)
y_test = np_utils.to_categorical(y_test, 10)
print(y_train.shape)

Using TensorFlow backend.


(60000, 10)


In [5]:
#import libraries....

from keras.datasets import mnist
from keras.models import Sequential, load_model
from keras.layers.core import Dense, Dropout, Activation




In [6]:
#model building ....

#layer 1.....
model = Sequential()
model.add(Dense(512, input_shape=(784,)))
model.add(Activation('relu'))                            
model.add(Dropout(0.2))
#layer 2......
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.2))

#final......
model.add(Dense(10))
model.add(Activation('softmax'))
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
activation_1 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               65664     
_________________________________________________________________
activation_2 (Activation)    (None, 128)               0         
_________________________________________________________________
dropout_2 (Dropout)  

In [7]:
#compiling model....
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
#fit the model...

fit_model = model.fit(X_train, y_train,epochs=20,batch_size=10000)

Instructions for updating:
Use tf.cast instead.
Epoch 1/20
60000/60000 [==============================] - 4s 70us/step - loss: 9.6850 - acc: 0.3822
Epoch 2/20
60000/60000 [==============================] - 2s 40us/step - loss: 5.5855 - acc: 0.6449
Epoch 3/20
60000/60000 [==============================] - 2s 40us/step - loss: 4.8325 - acc: 0.6949
Epoch 4/20
60000/60000 [==============================] - 2s 40us/step - loss: 4.2069 - acc: 0.7324
Epoch 5/20
60000/60000 [==============================] - 2s 40us/step - loss: 3.3643 - acc: 0.7850
Epoch 6/20
60000/60000 [==============================] - 2s 40us/step - loss: 3.0041 - acc: 0.8083
Epoch 7/20
60000/60000 [==============================] - 2s 40us/step - loss: 2.8490 - acc: 0.8189
Epoch 8/20
60000/60000 [==============================] - 2s 40us/step - loss: 2.6973 - acc: 0.8288
Epoch 9/20
60000/60000 [==============================] - 2s 40us/step - loss: 2.5937 - acc: 0.8355
Epoch 10/20
60000/60000 [===========================