In [1]:
#Creation of 1D array
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [2]:
#Creation of Boolean Array
import numpy as np
arr1=np.array([1,2,0,True,False],dtype=np.bool)
arr1

array([ True,  True, False,  True, False])

In [3]:
#Creation of 2D array
import numpy as np
l=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(l)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[a%2==1])

[1 3 5 7 9]


In [5]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[a%2==0]=0
print(a)


[[1 0 3]
 [0 5 0]
 [7 0 9]]


In [7]:
import numpy as np
a=np.array([33,33,13,44,55,66,77,55,12,23,21,34,59])
b=np.array([21,34,55,77])
x=b.argsort()
out=a[b[x[np.searchsorted(b,a,sorter=x)]]!=a]
print(out)

[33 33 13 44 66 12 23 59]


In [8]:
import numpy as np
a=np.array([1,5,8,3,6,9])
b=np.array([2,4,6,8,6,5])
result=np.where(a==b)
print(result)

(array([4]),)
