In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
train = pd.read_csv('/kaggle/input/integer-sequence-learning/train.csv.zip')
test = pd.read_csv('/kaggle/input/integer-sequence-learning/test.csv.zip')

In [3]:
train.head()

Id                                           Sequence
0   3  1,3,13,87,1053,28576,2141733,508147108,4021352...
1   7  1,2,1,5,5,1,11,16,7,1,23,44,30,9,1,47,112,104,...
2   8  1,2,4,5,8,10,16,20,32,40,64,80,128,160,256,320...
3  11  1,8,25,83,274,2275,132224,1060067,3312425,1099...
4  13  1,111,12211,1343211,147753211,16252853211,1787...

In [4]:
val = train.Sequence.values[0].split(',')

In [5]:
val

['1',
 '3',
 '13',
 '87',
 '1053',
 '28576',
 '2141733',
 '508147108',
 '402135275365',
 '1073376057490373',
 '9700385489355970183',
 '298434346895322960005291',
 '31479360095907908092817694945',
 '11474377948948020660089085281068730']

In [6]:
val_shaped = np.reshape(np.array(val),(7, 2))
val_shaped
X = [int(i[0]) for i in val_shaped]
y = [int(i[1]) for i in val_shaped]
X_shaped = np.reshape(np.array(X),(7,1))
y_shaped = np.reshape(np.array(y),(7,1))

In [7]:
X_shaped

array([[1],
       [13],
       [1053],
       [2141733],
       [402135275365],
       [9700385489355970183],
       [31479360095907908092817694945]], dtype=object)

In [8]:
y_shaped

array([[3],
       [87],
       [28576],
       [508147108],
       [1073376057490373],
       [298434346895322960005291],
       [11474377948948020660089085281068730]], dtype=object)

In [9]:
from sklearn.preprocessing import PolynomialFeatures 
from sklearn.linear_model import LinearRegression
  
poly = PolynomialFeatures(len(X))
X_poly = poly.fit_transform(X_shaped)
  
# fit the transformed features to Linear Regression
poly_model = LinearRegression()
poly_model.fit(X_poly, y_shaped)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
predicted = poly_model.predict(X_poly)
predicted

array([[4.97390513e+22],
       [4.97390513e+22],
       [4.97390513e+22],
       [4.97390513e+22],
       [4.97390513e+22],
       [4.97390513e+22],
       [1.14743779e+34]])

In [11]:
y_shaped

array([[3],
       [87],
       [28576],
       [508147108],
       [1073376057490373],
       [298434346895322960005291],
       [11474377948948020660089085281068730]], dtype=object)

In [12]:
predicted

array([[4.97390513e+22],
       [4.97390513e+22],
       [4.97390513e+22],
       [4.97390513e+22],
       [4.97390513e+22],
       [4.97390513e+22],
       [1.14743779e+34]])

In [13]:
y_shaped[6][0] -predicted[6][0]

0.0

As we can see, our last sequence 1.14743779e+34 is predicted %100 accurate with polynomial regression.