In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/boston-housing-dataset/HousingData.csv


In [2]:
import matplotlib.pyplot as plt
df=pd.read_csv('../input/boston-housing-dataset/HousingData.csv')

In [3]:
print(df)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93   0.0  0.573  6.030   NaN  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  3

In [4]:
 df.shape

(506, 14)

In [5]:
 df.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD          int64
TAX          int64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
dtype: object

In [6]:
df['RAD'] = df['RAD'].astype('float64')
df['TAX'] = df['TAX'].astype('float64')

In [7]:
 df.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
dtype: object

In [8]:
df.isnull().any()

CRIM        True
ZN          True
INDUS       True
CHAS        True
NOX        False
RM         False
AGE         True
DIS        False
RAD        False
TAX        False
PTRATIO    False
B          False
LSTAT       True
MEDV       False
dtype: bool

In [9]:
df.dropna(inplace=True)

In [10]:
df.isnull().any()

CRIM       False
ZN         False
INDUS      False
CHAS       False
NOX        False
RM         False
AGE        False
DIS        False
RAD        False
TAX        False
PTRATIO    False
B          False
LSTAT      False
MEDV       False
dtype: bool

In [11]:
df['CHAS'].value_counts(dropna=False)

0.0    367
1.0     27
Name: CHAS, dtype: int64

In [12]:
df1 = df[['CRIM','ZN','INDUS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV','CHAS']]
print(df1)

        CRIM    ZN  INDUS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0    0.00632  18.0   2.31  0.538  6.575  65.2  4.0900  1.0  296.0     15.3   
1    0.02731   0.0   7.07  0.469  6.421  78.9  4.9671  2.0  242.0     17.8   
2    0.02729   0.0   7.07  0.469  7.185  61.1  4.9671  2.0  242.0     17.8   
3    0.03237   0.0   2.18  0.458  6.998  45.8  6.0622  3.0  222.0     18.7   
5    0.02985   0.0   2.18  0.458  6.430  58.7  6.0622  3.0  222.0     18.7   
..       ...   ...    ...    ...    ...   ...     ...  ...    ...      ...   
499  0.17783   0.0   9.69  0.585  5.569  73.5  2.3999  6.0  391.0     19.2   
500  0.22438   0.0   9.69  0.585  6.027  79.7  2.4982  6.0  391.0     19.2   
502  0.04527   0.0  11.93  0.573  6.120  76.7  2.2875  1.0  273.0     21.0   
503  0.06076   0.0  11.93  0.573  6.976  91.0  2.1675  1.0  273.0     21.0   
504  0.10959   0.0  11.93  0.573  6.794  89.3  2.3889  1.0  273.0     21.0   

          B  LSTAT  MEDV  CHAS  
0    396.90   4.98  24.0   0.0

In [13]:
df1 = df1.dropna()

In [14]:
df.shape

(394, 14)

In [15]:
X = df1.iloc[:, :-1].values
y = df1.iloc[:,13].values

In [16]:
df1.dtypes

CRIM       float64
ZN         float64
INDUS      float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
CHAS       float64
dtype: object

In [17]:
X.shape

(394, 13)

In [18]:
y.shape

(394,)

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size =0.2,random_state =0)

In [20]:
X_train

array([[9.60400e-02, 4.00000e+01, 6.41000e+00, ..., 3.96900e+02,
        2.98000e+00, 3.20000e+01],
       [6.58800e-02, 0.00000e+00, 2.46000e+00, ..., 3.95560e+02,
        7.56000e+00, 3.98000e+01],
       [2.41030e-01, 0.00000e+00, 7.38000e+00, ..., 3.96900e+02,
        1.27900e+01, 2.22000e+01],
       ...,
       [1.62864e+00, 0.00000e+00, 2.18900e+01, ..., 3.96900e+02,
        3.44100e+01, 1.44000e+01],
       [1.43200e-02, 1.00000e+02, 1.32000e+00, ..., 3.92900e+02,
        3.95000e+00, 3.16000e+01],
       [1.10690e-01, 0.00000e+00, 1.38900e+01, ..., 3.96900e+02,
        1.79200e+01, 2.15000e+01]])

In [21]:
y_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [22]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
y_pred =regressor.predict(X_test)

In [24]:
import statsmodels.formula.api as sm
X = np.append(arr=np.ones((394,1)).astype(int),values=X,axis=1)

In [25]:
print(X)

[[1.0000e+00 6.3200e-03 1.8000e+01 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [1.0000e+00 2.7310e-02 0.0000e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [1.0000e+00 2.7290e-02 0.0000e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [1.0000e+00 4.5270e-02 0.0000e+00 ... 3.9690e+02 9.0800e+00 2.0600e+01]
 [1.0000e+00 6.0760e-02 0.0000e+00 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0000e+00 1.0959e-01 0.0000e+00 ... 3.9345e+02 6.4800e+00 2.2000e+01]]


In [26]:
import statsmodels.api as sm

In [27]:
X_opt = X[:,:13] 
regressor_OLS=sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.065
Model:                            OLS   Adj. R-squared:                  0.035
Method:                 Least Squares   F-statistic:                     2.197
Date:                Mon, 14 Oct 2019   Prob (F-statistic):             0.0114
Time:                        13:44:34   Log-Likelihood:                -3.8375
No. Observations:                 394   AIC:                             33.68
Df Residuals:                     381   BIC:                             85.37
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0735      0.315      0.234      0.815      -0.545       0.692
x1            -0.0023      0.002     -1.267      0.206      -0.006       0.001
x2             0.0002      0.001      0.282      0.778      -0.001       0.002
x3             0.0066      0.004      1.811      0.071      -0.001       0.014
x4             0.0620      0.235      0.264      0.792      -0.400       0.524
x5             0.0286      0.026      1.101      0.272      -0.023       0.080
x6             0.0004      0.001      0.454      0.650      -0.001       0.002
x7            -0.0080      0.012     -0.685      0.494      -0.031       0.015
x8             0.0100      0.004      2.626      0.009       0.003       0.017
x9            -0.0006      0.000     -2.533      0.012      -0.001      -0.000
x10           -0.0133      0.008     -1.718      0.087      -0.029       0.002
x11            0.0003      0.000      1.668      0.096   -4.89e-05       0.001
x12           -0.0001      0.003     -0.046      0.963      -0.006       0.006
==============================================================================
Omnibus:                      264.895   Durbin-Watson:                   1.346
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1727.876
Skew:                           3.055   Prob(JB):                         0.00
Kurtosis:                      11.241   Cond. No.                     1.57e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.57e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [28]:
X_opt =X[:,[1,3,5,7,8,9,10,11,12]]
regressor_OLS=sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.127
Model:                            OLS   Adj. R-squared (uncentered):              0.107
Method:                 Least Squares   F-statistic:                              6.241
Date:                Mon, 14 Oct 2019   Prob (F-statistic):                    3.05e-08
Time:                        13:44:34   Log-Likelihood:                         -4.1702
No. Observations:                 394   AIC:                                      26.34
Df Residuals:                     385   BIC:                                      62.13
Df Model:                           9                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.0023      0.002     -1.274      0.203      -0.006       0.001
x2             0.0072      0.003      2.107      0.036       0.000       0.014
x3             0.0420      0.013      3.166      0.002       0.016       0.068
x4            -0.0091      0.008     -1.092      0.276      -0.026       0.007
x5             0.0096      0.004      2.694      0.007       0.003       0.017
x6            -0.0005      0.000     -2.504      0.013      -0.001      -0.000
x7            -0.0126      0.006     -2.223      0.027      -0.024      -0.001
x8             0.0003      0.000      1.969      0.050    3.83e-07       0.001
x9             0.0012      0.002      0.487      0.626      -0.004       0.006
==============================================================================
Omnibus:                      265.463   Durbin-Watson:                   1.341
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1736.862
Skew:                           3.062   Prob(JB):                         0.00
Kurtosis:                      11.264   Cond. No.                         614.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [29]:
X_opt =X[:,[1,3,5,7,8,9,10,11]]
regressor_OLS=sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.127
Model:                            OLS   Adj. R-squared (uncentered):              0.109
Method:                 Least Squares   F-statistic:                              7.006
Date:                Mon, 14 Oct 2019   Prob (F-statistic):                    1.21e-08
Time:                        13:44:34   Log-Likelihood:                         -4.2918
No. Observations:                 394   AIC:                                      24.58
Df Residuals:                     386   BIC:                                      56.39
Df Model:                           8                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.0021      0.002     -1.202      0.230      -0.005       0.001
x2             0.0074      0.003      2.209      0.028       0.001       0.014
x3             0.0401      0.013      3.170      0.002       0.015       0.065
x4            -0.0095      0.008     -1.141      0.254      -0.026       0.007
x5             0.0095      0.004      2.660      0.008       0.002       0.016
x6            -0.0005      0.000     -2.461      0.014      -0.001      -0.000
x7            -0.0115      0.005     -2.229      0.026      -0.022      -0.001
x8             0.0003      0.000      1.956      0.051   -1.55e-06       0.001
==============================================================================
Omnibus:                      265.869   Durbin-Watson:                   1.339
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1745.686
Skew:                           3.067   Prob(JB):                         0.00
Kurtosis:                      11.290   Cond. No.                         581.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [30]:
X_opt =X[:,[3,5,8,9,10,11]]
regressor_OLS=sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.121
Model:                            OLS   Adj. R-squared (uncentered):              0.107
Method:                 Least Squares   F-statistic:                              8.903
Date:                Mon, 14 Oct 2019   Prob (F-statistic):                    4.09e-09
Time:                        13:44:35   Log-Likelihood:                         -5.5907
No. Observations:                 394   AIC:                                      23.18
Df Residuals:                     388   BIC:                                      47.04
Df Model:                           6                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0094      0.003      3.343      0.001       0.004       0.015
x2             0.0383      0.012      3.062      0.002       0.014       0.063
x3             0.0092      0.003      2.714      0.007       0.003       0.016
x4            -0.0005      0.000     -2.700      0.007      -0.001      -0.000
x5            -0.0135      0.005     -2.749      0.006      -0.023      -0.004
x6             0.0003      0.000      2.035      0.042    1.04e-05       0.001
==============================================================================
Omnibus:                      268.860   Durbin-Watson:                   1.329
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1803.574
Skew:                           3.102   Prob(JB):                         0.00
Kurtosis:                      11.448   Cond. No.                         574.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [31]:
X_opt =X[:,[0,1,4,10,14]]
regressor_OLS=sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

IndexError: index 14 is out of bounds for axis 1 with size 14